import os
HOME = os.getcwd()+"/2D-NACA0012/RANS"
os.chdir(HOME)
os.chdir("aeroOnly")
os.chdir("pureSU2")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir(HOME)
os.chdir("aeroOnly")
os.chdir("interface")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir(HOME)
os.chdir("static_aeroelasticity")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir(HOME)
os.chdir("forced_sine")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir(HOME)
os.chdir("dynamic_aeroelasticity")
os.chdir("Ma01")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir("..")
os.chdir("Ma02")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir("..")
os.chdir("Ma03")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir("..")
os.chdir("Ma0357")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir("..")
os.chdir("Ma0364")
os.system("rm *vtu FSI* Struct* log* histo*")
os.chdir("..")
os.chdir(HOME)
