import os
HOME = os.getcwd()+"/2D-NACA0012/RANS"
os.chdir("aeroOnly")
os.chdir("pureSU2")
os.system("mpirun -np 38 SU2_CFD fluid.cfg > log.txt")
os.chdir(HOME)
os.chdir("aeroOnly")
os.chdir("interface")
os.system("mpirun -np 38 python3 /scratch/aero/nfonzi/SU2/bin/fsi_computation.py --parallel -f fsi.cfg > log.txt")
os.chdir(HOME)
os.chdir("static_aeroelasticity")
os.system("mpirun -np 38 python3 /scratch/aero/nfonzi/SU2/bin/fsi_computation.py --parallel -f fsi.cfg > log.txt")
os.chdir(HOME)
os.chdir("forced_sine")
os.system("mpirun -np 38 python3 /scratch/aero/nfonzi/SU2/bin/fsi_computation.py --parallel -f fsi.cfg > log.txt")
os.chdir(HOME)
os.chdir("dynamic_aeroelasticity")
os.system("bash launch.sh")
os.chdir(HOME)
